runtime: python39

service_account: sky-api@sky-api-326214.iam.gserviceaccount.com

entrypoint: gunicorn -t 500 -b :$PORT main:app

instance_class: B4

basic_scaling: 
  max_instances: 10
  idle_timeout: 10m